name: Test & Deploy Python to GCP Functions

on:
  push:
    branches:
      - main   # despliega cuando haces push a main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run pytest
        run: pytest app/tests

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ secrets.GCP_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: 'Verify authentication'
        run: |
          gcloud auth list
          gcloud config list project

      - name: Deploy to Cloud Functions Gen2
        run: |
          gcloud functions deploy ${{ secrets.GCP_FUNCTION_NAME }} \
            --gen2 \
            --runtime python311 \
            --trigger-http \
            --allow-unauthenticated \
            --region ${{ secrets.GCP_REGION }} \
            --source=. \
            --entry-point=get_menu \
            --memory=512Mi \
            --timeout=300s \
            --min-instances=0 \
            --max-instances=100