name: Test & Deploy Python to GCP Functions

on:
  push:
    branches:
      - main   # despliega cuando haces push a main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run pytest
        run: pytest app/tests

  deploy:
    needs: test   # solo corre si los tests pasan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true

      - name: Deploy to Cloud Functions
        run: |
          gcloud functions deploy ${{ secrets.GCP_FUNCTION_NAME }} \
            --runtime python311 \
            --trigger-http \
            --allow-unauthenticated \
            --region ${{ secrets.GCP_REGION }}
